---
title: "Visualizing Dendrogram using ggtree"
author: 
- name: Guangchuang Yu
  email: guangchuangyu@gmail.com
  affiliation: Department of Bioinformatics, School of Basic Medical Sciences, Southern Medical University
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
  pdf_document:
    toc: true
vignette: >
  %\VignetteIndexEntry{Visualizing Dendrogram using ggtree}
  %\VignetteEngine{knitr::rmarkdown}
  %\usepackage[utf8]{inputenc}
  %\VignetteEncoding{UTF-8}
---

```{r style, echo=FALSE, results="asis", message=FALSE}
knitr::opts_chunk$set(tidy = FALSE,
                      warning = FALSE,
                      message = FALSE)
library(yulab.utils)                      
```


```{r}
library(ggtree)
library(ggtreeDendro)
library(aplot)
```

## `hclust` and `dendrogram` objects

These two classes are defined in the `r CRANpkg("stats")` package.

```{r fig.width=16, fig.height=6}
d <- dist(USArrests)

hc <- hclust(d, "ave")
den <- as.dendrogram(hc)

p1 <- autoplot(hc) + geom_tiplab()
p2 <- autoplot(den)
plot_list(p1, p2, ncol=2)
```


## `linkage` object

The class `linkage` is defined in the `r CRANpkg("mdendro")` package.

```{r fig.width=8, fig.height=8}
library("mdendro")
lnk <- linkage(d, digits = 1, method = "complete")
autoplot(lnk, layout = 'circular') + geom_tiplab() + 
  scale_color_subtree(4) + theme_tree()
```

## `agnes`, `diana` and `twins` objects

These classes are defined in the `r CRANpkg("cluster")` package.

```{r fig.width=16, height=6}
library(cluster)
x1 <- agnes(mtcars)
x2 <- diana(mtcars)

p1 <- autoplot(x1) + geom_tiplab()
p2 <- autoplot(x2) + geom_tiplab()
plot_list(p1, p2, ncol=2)
```


## `pvclust` object

The `pvclust` class is defined in the `r CRANpkg("pvclust")` package.


```{r fig.width=8, height=6}
library(pvclust)
data(Boston, package = "MASS")

set.seed(123)
result <- pvclust(Boston, method.dist="cor", method.hclust="average", nboot=1000, parallel=TRUE)
autoplot(result)
```